nnstreamer: Update demo script
Update nnstreamer_example_object_detection_uvc.py to fix error:
===
gi.repository.GLib.GError: gst_parse_error: no element "v4l2convert" (1)
===

For UVC camera, use videoconvert to convert format instead of v4l2convert.

CR-Id: AUTO00252885
Change-Id: I212e1888f2bd0b7d174135205b2218e8d4c9b531
Signed-off-by: kidd-kw.chen <kidd-kw.chen@mediatek.com>